# Site
title:              Minbiao Han
bio:                'Computer Science PhD Student | UVA'
description:        ""
reading_time:       true
words_per_minute:   200
logo:               'assets/img/MinbiaoHan.jpg'
background:         'assets/img/bg2.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://francisdavis.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   mdothan

# Social
# if you don't have any of social below, comment the line.
google:
  plus:            minbiao.han
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              minbiao.han@email.virginia.edu
#facebook:           username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          minbiaohan
#xing:              username
instagram:          imdothan
github-url:         Minbiao-Han
#twitter:            username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
